config/routes.rb
Rating::Application.routes.draw do
  resources :products
  resources :rates
	match '/product/:id/rate'	=>"products#rateit"

   root :to => 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name
  has_many :rates
  
  def average_rating
  	users = self.rates.count
	 	users = users != 0 ? users : 1.0
	 	average = self.rates.sum(:vote) / users
  	average.round(2)
  end
  
  def rate_by_user(user,vote)
		rate = self.rates.where("user_id = ? ",user.id).first
		rate = rate.present? ? rate : self.rates.create(:user_id=>user.id)
		rate.vote = vote
		rate.save
		rate
  end
  
  def rate_by_ip(ip,vote)
	  rate = self.rates.where("ip_address like ? ",ip).first  	
		rate = rate.present? ? rate : self.rates.create(:ip_address=>ip)
		rate.vote = vote
		rate.save
		rate
	end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  attr_accessible :ip_address, :product_id, :user_id, :vote
  belongs_to :user
  belongs_to :product 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
  
  def rateit
		  @product = Product.find(params[:id])

		#  if current_user.present?
		 #    rate = @product.rate_by_user(current_user,params[:vote])
		 # else
					 rate = @product.rate_by_ip(request.remote_ip,params[:vote])		 			
		  #end
	 		render :text=>@product.average_rating.to_s
	 		return
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rating</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    </tr>
  <tr>
  	<td colspan="4">
  		<div id="<%=product.id%>" class="rateit" data-rateit-value="<%=product.average_rating%>"></div>
  		<div>
		    <span id="value-<%=product.id%>"></span>
			</div>
		</td>
  </tr>
  
<% end %>
</table>

<br />


<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>